### ISSUE TITLE
Implement power-ups

### ISSUE THREAD

**Issue by EdvardX** [EdvardX/Jumping-Frog#10]
- Add power-ups that provide temporary advantages (e.g., invincibility, speed boost).
- Place power-ups at random locations on the road.

**Tasks**:
- [ ] Implement power-up spawning logic.
- [ ] Implement power-up effects.
- [ ] Test power-ups.
