### ISSUE TITLE
Implement collision detection

### ISSUE THREAD

**Issue by EdvardX** [EdvardX/Jumping-Frog#3]
- Detect collisions between the frog and cars.
- Deduct a life if a collision occurs.
- Reset frog position after a collision.

**Tasks**:
- [ ] Implement collision detection function.
- [ ] Update game state on collision.
- [ ] Deduct a life if a collision occurs.
- [ ] Reset frog position after a collision.
- [ ] Test collision detection.
