### ISSUE TITLE
Implement save game functionality

### ISSUE THREAD

**Issue by EdvardX** [EdvardX/Jumping-Frog#7]
- Allow the player to save the game progress by pressing a specific key.
- Store the game state in a file.

**Tasks**:
- [ ] Implement save game function.
- [ ] Store game state in a file.
- [ ] Test save game functionality.
