### ISSUE TITLE
Implement load game functionality

### ISSUE THREAD

**Issue by EdvardX** [EdvardX/Jumping-Frog#8]
- Allow the player to load previously saved game progress.
- Restore the game state from the saved file.

**Tasks**:
- [ ] Implement load game function.
- [ ] Read game state from file.
- [ ] Test load game functionality.
