### ISSUE TITLE
Add coins for the frog to collect

### ISSUE THREAD

**Issue by EdvardX** [EdvardX/Jumping-Frog#9]
- Place coins on the road for the frog to collect.
- Increase the score when a coin is collected.

**Tasks**:
- [ ] Implement coin spawning logic.
- [ ] Implement coin collection logic.
- [ ] Update score on coin collection.
- [ ] Test coin collection.
